### ISSUE TITLE
Time-dependent negative sampling

### ISSUE THREAD

**Issue by alittlealone** [malllabiisc/HyTE#6]
Thanking for sharing your code! 
I'm having a hard time figuring out how you implement the "time-dependent negative sampling(TDNS)" in your paper, can you help me on this? I think the negative sampling process is implemented in line 243-270 of "time_proj.py", isn't this the normal sampling(or "TANS" in your paper)? Or did I miss something?

**Comment by ssdasgupta** [comment]
@alittlealone , please find the TDNS code here: https://github.com/malllabiisc/HyTE/blob/master/time_proj_tdns_scope.py 
Let me know if you have any questions about it.

**Comment by alittlealone** [comment]
I can't believe I just ignored the file time_proj_tdns_scope.py. Thank you for your help!

**Comment by ssdasgupta** [comment]
Absolutely no problem. Best of luck @alittlealone .
