### ISSUE TITLE
No Code for hit@10 in result_eval.py. 

### ISSUE THREAD

**Issue by smitsunny11** [malllabiisc/HyTE#7]
I couldn't find any code to calculate hit@10 metric for the tail and head prediction in the result_eval file. 
So, I wrote a piece of code after the line number 68. Let me know if it is correct or not?

tail_array = np.array(ranks_tail)
head_array = np.array(ranks_head)

hit_at_10_tail = tail_array[np.where( tail_array < 10 ) ]
hit_at_10_head = head_array[np.where( head_array < 10 ) ]

print('Epoch {} :  test_tail HIT@10 {}\t test_head HIT@!) {}'.format(k ,len(hit_at_10_tail)/float(len(tail_array))*100, len(hit_at_10_head)/float(len(head_array))*100))

**Comment by SwayambhuNathRay** [comment]
Hi Smit,
          This code looks fine to me. We will update result_eval.py to
output hits@10. Sorry for the inconvenience caused.
