### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by 876012988** [malllabiisc/HyTE#8]
```shell
  python time_proj.py -data_type yago -margin 10 -model MODEL_NAME -test_freq 25 
  ```
hello，I cannot find the parameter  MODEL_NAME.

**Comment by SwayambhuNathRay** [comment]
Hello Kyan,
               The "model" parameter you are searching for corresponds to
the "name" parameter in time_proj.py. This parameter is used to give a name
to every run of the model and save checkpoints using this name. Sorry for
the confusion. We will take care of this and update the code.
